### ISSUE TITLE
Uniquely identifying human intervention deployments

### ISSUE THREAD

**Issue by nicolasreed** [SwissTPH/openmalaria#116]
Currently, it does not appear that there is any restriction on having multiple deployments with the same name in the `<human>` section of `<interventions>`. I am not certain whether this is worth changing, but wanted to see whether or not having a separate unique id (or requiring names to be unique) would be of any benefit.

Note: I could see this change being of some benefit to [this PR](https://github.com/vecnet/vecnet.openmalaria/pull/39) for vecnet.openmalaria.

Thoughts?

**Comment by dhardy** [comment]
Which are you referring to exactly?

Each `interventions/human/component` element must have a unique id by design. Probably this is enforced by the simulator code but not by the XML because I didn't know how to do that.

The `interventions/human/deployment/component` elements can refer to any id. By design, two different `deployment` elements can list the same `component` id. Within one `deployment` element, each `component` id *should* be unique but I don't remember whether this is enforced or know if it would actually cause a problem.

**Comment by dhardy** [comment]
Oh, the `name` tag is purely for the user's description, like many of the other `name` tags in the schema.

**Comment by nicolasreed** [comment]
Thanks for the help.

Resolved. See [my comment](https://github.com/vecnet/vecnet.openmalaria/pull/39#issuecomment-113844104) for why.
