### ISSUE TITLE
Clarify usage of issue tracker

### ISSUE THREAD

**Issue by dhardy** [SwissTPH/openmalaria#145]
@tph-thuering @ThomasASmith 

What do the following labels mean?

*   bug
*   defect
*   task
*   software engineering

My thoughts are to replace `bug` and `defect` with `compile-issue`, `crash` and `wrong-output`, and remove the others listed (unless there is some meaning I'm missing).

**Comment by nakul7** [comment]
I agree. Best,

Nakul

On 2015-10-27 17:03, Diggory Hardy wrote:
>
> @tph-thuering <https://github.com/tph-thuering> @ThomasASmith 
> <https://github.com/ThomasASmith>
>
> What do the following labels mean?
>
>   * bug
>   * defect
>   * task
>   * software engineering
>
> My thoughts are to replace |bug| and |defect| with |compile-issue|, 
> |crash| and |wrong-output|, and remove the others listed (unless there 
> is some meaning I'm missing).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SwissTPH/openmalaria/issues/145>.
>

-- 
Nakul Chitnis
Department of Epidemiology and Public Health
Swiss Tropical and Public Health Institute
Socinstrasse 57, Postfach,
CH-4002 Basel
Switzerland
Tel: +41 61 284 82 42
Fax: +41 61 284 81 05
Email: Nakul.Chitnis@unibas.ch

**Comment by dhardy** [comment]
Also, maybe we should agree on a meaning for priorities; "critical" and "high" obviously mean this needs doing, and I have labelled many things "low" where they are not something I have any intention of ever doing unless prompted by some related issue.

**Comment by ThomasASmith** [comment]
I propose:
- Critical means to be dealt with immediately.
- High means that the person assigned this should try to address it without waiting for anyone else to give the go-ahead.
- Medium means go ahead with this if you can do it easily and conveniently, but don't invest significant time or energy in it.
- Low (following Diggory's suggestion) means "not something anyone will do unless prompted by some related issue".

I propose that priority setting should be the prerogative of me as project leader.  Anyone can suggest a priority for something but I might over-rule them.  Since I have to allocate resources I need to be able to decide when we can't afford to do something, but there are some technical issues where I can't judge the priority, so I will probably defer to others' assignments on these.  I will try to ensure that every issue has a priority.

**Comment by dhardy** [comment]
@tph-thuering I would still like to know what `task` and `software engineering` mean.

Another type of "defect" would of course be `documentation` (wiki or simulator output).

**Comment by ThomasASmith** [comment]
I think the labels   `task` and `software engineering` could be removed.

**Comment by dhardy** [comment]
I think this is sorted then.

Still not sure what `ready` means but never mind.

**Comment by tph-thuering** [comment]
@dhardy ready was set by waffle.io https://waffle.io/SwissTPH/openmalaria

**Comment by dhardy** [comment]
@tph-thuering darn, looks like I shouldn't have renamed those labels then (the `status-....` ones)

**Comment by tph-thuering** [comment]
@dhardy that is okay. I guess I could configure waffle.io to use the label we use.

**Comment by dhardy** [comment]
I renamed them back. Annoying thing is it still doesn't work. Anyway, I don't care much about waffle.
