### ISSUE TITLE
Results/output format revision

### ISSUE THREAD

**Issue by dhardy** [SwissTPH/openmalaria#159]
@Baguage brought up that file formats should be easier to parse and should include age groups within the output file. Any further requests?

@ThomasASmith @tph-thuering Is it worth discussing this in the group meeting? Is there much interest?

**Comment by ThomasASmith** [comment]
I'm reluctant to endorse any changes of formats that might break old post-processing software.  If it won't break this then why not.  I suppose there is a case for generating a configuration file that contains the Information about how to read the .txt, but since the information required for this is in the .xml perhaps this is redundant.

**Comment by dhardy** [comment]
I think changes would have to be optional: either a choice of the old or new output format, or making the whole thing quite flexible (which doesn't seem that hard, but might be confusing if every experiment uses a different format).

Good point about generating a second file for how to read the main output file; it would be redundant, yes, but might have some uses (e.g. it would probably be invariant in an experiment, so would only have to be generated once). I think Alex wanted something like this.

**Comment by tph-thuering** [comment]
@dhardy: I would suggest we add a new argument option to output this in 
a different format _if_ you are possibly thinking about JSON output. 
Then we don't break peoples software/workflow. But maybe this is too 
much code to refactor..

On 04/08/2016 06:09 PM, Diggory Hardy wrote:
>
> @Baguage <https://github.com/Baguage> brought up that file formats 
> should be easier to parse and should include age groups within the 
> output file. Any further requests?
>
> @ThomasASmith <https://github.com/ThomasASmith> @tph-thuering 
> <https://github.com/tph-thuering> Is it worth discussing this in the 
> group meeting? Is there much interest?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/SwissTPH/openmalaria/issues/159>
>

-- 
Tobias Thüring | Technical Staff
Biozentrum, University of Basel & SIB Swiss Institute of Bioinformatics
Klingelbergstrasse 50/70 | CH-4056 Basel | Office: +41 61 267 15 83
Email: tobias.thuering@unibas.ch | www.biozentrum.unibas.ch/schwede/

**Comment by dhardy** [comment]
I was thinking an option in the XML input file, though a command line option is another possibility.

I don't see any real advantage to JSON output. It's non-trivial to load into a spreadsheet and considering our outputs can be fairly large would add quite a bit of overhead to processing.

I was thinking more along the lines of like the current format, but extra columns instead of the tricks we use now to output cohort group or parasite genotype, and either a *preamble* or separate file as a key.

**Comment by tph-thuering** [comment]
Hi,

I was just thinking about how this situation could be improved _when_ 
using an alternative output format.

Rather than writing everything into 1 file in the first place, we could 
output 1 file for every measure/dimension and in a second step 
post-process that rather than trying to cram every measure into 1 line.

With using JSON there are a lot of tools available to post-process it 
and bring it easily into that csv-format which is simple to import into 
excel.

Have a look at "[jq](https://stedolan.github.io/jq/)" if you don't know 
already for example. map, reduce, zip, unzip comes into mind...

For example:

Current situation:

With 3 surveys (1,2,3), and measures (0,1,31), 2 vector species (0,1) 
and 2 agegroups (0,1) we get the following in 1 file:

output.txt:
```
1    0    0    n
1    0    1    m
1    0    31    o
1    1    0    p
1    1    1    q
1    1    31    r
2    0    0    n
2    0    1    m
2    0    31    o
2    1    0    p
2    1    1    q
2    1    31    r
3    0    0    n
3    0    1    m
3    0    31    o
3    1    0    p
3    1    1    q
3    1    31    r
```
If we write the whole thing out separately we get 3 files:

measure-0.json:
```
{
     measure_no: 0,
     measure_name: "nHost",
     survey_steps: 3,
     survey_interval: "1n",
     dimension: "age group",
     dimension_values: [0,1],
     survey: {
         0: [n,n,n],
         1: [p,p,p]
     }
}
```

measure-1.json:
```
{
     measure_no: 1,
     measure_name: "nInfect",
     survey_steps: 3,
     survey_interval: "1n",
     dimension: "age group",
     dimension_values: [0,1],
     survey: {
         0: [m,m,m],
         1: [q,q,q]
     }
}
```

measure-31.json:
```
{
     measure_no: 31,
     measure_name: "Vector_Nv0",
     survey_steps: 3,
     survey_interval: "1n",
     dimension: "vector species",
     dimension_values: [0,1],
     survey: {
         0: [o,o,o],
         1: [r,r,r]
     }
}
```

On 04/12/2016 11:32 AM, Diggory Hardy wrote:
>
> I was thinking an option in the XML input file, though a command line 
> option is another possibility.
>
> I don't see any real advantage to JSON output. It's non-trivial to 
> load into a spreadsheet and considering our outputs can be fairly 
> large would add quite a bit of overhead to processing.
>
> I was thinking more along the lines of like the current format, but 
> extra columns instead of the tricks we use now to output cohort group 
> or parasite genotype, and either a /preamble/ or separate file as a key.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/SwissTPH/openmalaria/issues/159#issuecomment-208815414>
>

-- 
Tobias Thüring | Technical Staff
Biozentrum, University of Basel & SIB Swiss Institute of Bioinformatics
Klingelbergstrasse 50/70 | CH-4056 Basel | Office: +41 61 267 15 83
Email: tobias.thuering@unibas.ch | www.biozentrum.unibas.ch/schwede/

**Comment by ThomasASmith** [comment]
The output format is not currently a bottleneck so I do not currently support making any changes to it. This would either (i) create unused functionality, or (ii) break existing output processing software.
