### ISSUE TITLE
Automate builds for SciCore 

### ISSUE THREAD

**Issue by ThomasASmith** [SwissTPH/openmalaria#164]
This was discussed at the MMC group meeting on 21 June 2016. 
Not sure how this relates to #87, #144, #157

**Comment by tph-thuering** [comment]
#144 and #157 are unrelated, since we build with gcc on bc2, it might 
not be trivial to use another toolchain.

#87 does make much sense in the current bc2-environment, since we can't 
install some dependencies on the cluster (version-conflicts).
It would make more sense to build an lmod-package or just use the 
binaries provided in our group-folder for each release.

I don't know exactly how I would be able to automate this, but using the 
build-script I've created makes it easy to start new builds.

I will check with the SciCore/bc2 guys on how we could do this with 
git-hooks or something similar.


On 06/22/2016 11:18 AM, ThomasASmith wrote:
>
> This was discussed at the MMC group meeting on 21 June 2016.
> Not sure how this relates to #87 
> <https://github.com/SwissTPH/openmalaria/issues/87>, #144 
> <https://github.com/SwissTPH/openmalaria/issues/144>, #157 
> <https://github.com/SwissTPH/openmalaria/pull/157>
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/SwissTPH/openmalaria/issues/164>, or mute the 
> thread 
> <https://github.com/notifications/unsubscribe/AJQFl78z3_xeJ9HLk_93nnl86jY6P2xVks5qOP3lgaJpZM4I7kTO>.
>

-- 
Tobias Thüring | Technical Staff
Biozentrum, University of Basel & SIB Swiss Institute of Bioinformatics
Klingelbergstrasse 50/70 | CH-4056 Basel | Office: +41 61 267 15 83
Email: tobias.thuering@unibas.ch | www.biozentrum.unibas.ch/schwede/

**Comment by tph-thuering** [comment]
There might be a possibility to use their gitlab-instance with gitlab-runners to build and publish a software-package of OpenMalaria for SciCore.

**Comment by tph-thuering** [comment]
It seems SciCore's gitlab-service is quite well established in the university by now. Maybe we could try to continue this. @ThomasASmith what do you think? Has this still high priority?

**Comment by ThomasASmith** [comment]
This still has considerable priority as far as I understand it since most users are using SciCore, although @dhardy seems to have been generating new builds without it.. He can best comment on what are the current requirements for efficient generation of new builds.

**Comment by dhardy** [comment]
I don't know. OpenMalaria as a whole seems to be "gathering dust" by continuing to use old tooling. I had a build problem the other day because we still use C++98 and my installation of xerces was built for C++11 (or later).

If @tph-thuering would try doing a simple build on SciCore (usually it's not hard building on Linux systems) and tell me if there are any library/tooling incompatibilities, I could try updating those. It's probably worth switching to C++11 now (or even 14 or 17); the new standards are supposed to be backwards compatible so it shouldn't be too hard.

**Comment by dhardy** [comment]
I don't know what services SciCore has for automated builds — @tph-thuering perhaps you know where to start with this gitlab-runner? Does this require setting up a gitlab mirror of the github repo, or using webhooks for notification?

We've now switched to C++11 so there shouldn't be any issues using modern tooling to build OpenMalaria.

**Comment by dhardy** [comment]
@Monica-Golumbeanu have you sorted out builds on SciCore?

**Comment by ThomasASmith** [comment]
SciCore do not allow other people adminstrator rights.

The solution to this is to put OpenMalaria in a container as described at:

https://github.com/SwissTPH/openmalaria/wiki/OpenMalariaContainer
