### ISSUE TITLE
Nv threshold for extinction of vector species

### ISSUE THREAD

**Issue by ManuelaRunge** [SwissTPH/openmalaria#214]
The vector populations will always recover and never reach extinction (only very small numbers in Nv). 
For certain simulations the extinction of a vector species is wanted.
Workarounds are to set the threshold  manually after simulations were run, or to just keep the intervention ongoing for forever, which is not optimal.

**Comment by dhardy** [comment]
We added thresholds for the elimination of infected mosquitoes at some point. Is this as simple as adding a threshold for elimination of the mosquito or might there be issues with models? E.g. should elimination of one mosquito species allow another to proliferate due to reduced competition — I don't think we ever got the model for this working ("simple MPD" is a simplified version of @nakul7's full model; I think we had some problems getting the full version working).

**Comment by ManuelaRunge** [comment]
It would be a simple addition of a threshold for Nv. However, it in most simulations one would want the vector population to re-establish, depending on the research question. In discussion with @nakul7  and @ThomasASmith  we had agreed on the workaround, to set the threshold on Nv in the analysis of simulation results outside OpenMalaria.
