### ISSUE TITLE
Vectors: cross-species resource competition

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SwissTPH/openmalaria#41]
```
Olivier's model: Funestus and Arabiensis larvae shouldn't compete with each
other at all, while indoor-biting and outdoor-biting Arabiensis larvae should
compete for the same resources. Should extend SimpleMPD model to allow this.
```

Original issue reported on code.google.com by `diggory....@gmail.com` on 27 Nov 2013 at 12:12

**Comment by dhardy** [comment]
@nakul7 @ThomasASmith 

I've been considering how to model this. [Equation 2a,b](https://openmalaria.googlecode.com/svn/download/articles/MosquitoLifeCycleSimplePer.pdf) gives the emergence from the current model. `y(t-θj)` is the number of female eggs laid at the right time in the past to hatch now.

It seems to me that the `y(t-θj)` term in the numerator should be eggs laid for the current species of mosquito while the term in the denominator should be eggs laid for all competing mosquito species. This should be simple to implement, but has one oddity: `θj` (time from egg to emergence) is specific to the mosquito species. We can probably just overlook this.

Likely more pertinent is that with the simple model there will be no forcing of the proportion of emerging mosquitoes belonging to each species, thus it would not surprise me if one species frequently ends up eliminating all other competing species in simulations even where all are equally efficient at reproduction. Perhaps this could be prevented by imposing an efficiency penalty on resources used from "other" species? (During initialisation, the resources required by each species is calculated.)

**Comment by ThomasASmith** [comment]
As with the parasite genotypes, the different species will need to 
differ in some parameters if they are to co-exist.  We would want to 
simulate situations where the adults have a survival advantage in one 
species and the larvae in the competing one; I suspect there is quite a 
lot ecological theory on life course competition- where the adults of 
one species have an advantage, and the young of the other one.

We should have at least one parameter of the larval life cycle that 
differs by species, otherwise Diggory is right that we will probably 
have difficulty in simulating  co-existence of multiple competing 
species. It is probably not critical whether this is time from egg to 
emergence if there are other parameters that could vary, but we should 
keep it as simple as possible as we will probably never have field data 
to parameterise these models.

On 20.06.2015 21:32, Diggory Hardy wrote:
>
> @nakul7 <https://github.com/nakul7> @ThomasASmith 
> <https://github.com/ThomasASmith>
>
> I've been considering how to model this. Equation 2a,b 
> <https://openmalaria.googlecode.com/svn/download/articles/MosquitoLifeCycleSimplePer.pdf> 
> gives the emergence from the current model. |y(t-θj)| is the number of 
> female eggs laid at the right time in the past to hatch now.
>
> It seems to me that the |y(t-θj)| term in the numerator should be eggs 
> laid for the current species of mosquito while the term in the 
> denominator should be eggs laid for all competing mosquito species. 
> This should be simple to implement, but has one oddity: |θj| (time 
> from egg to emergence) is specific to the mosquito species. We can 
> probably just overlook this.
>
> Likely more pertinent is that with the simple model there will be no 
> forcing of the proportion of emerging mosquitoes belonging to each 
> species, thus it would not surprise me if one species frequently ends 
> up eliminating all other competing species in simulations even where 
> all are equally efficient at reproduction. Perhaps this could be 
> prevented by imposing an efficiency penalty on resources used from 
> "other" species? (During initialisation, the resources required by 
> each species is calculated.)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SwissTPH/openmalaria/issues/41#issuecomment-113809396>.
>


-- 
Thomas Smith
Swiss Tropical & Public Health Institute
Department of Epidemiology & Public Health
Socinstrasse 57
P.O . Box
CH-4002 Basel
Switzerland
Tel  +41 61 284 8273 Fax +41 61 284 8101
email: Thomas-A.Smith@unibas.ch
http://www.swisstph.ch/about-us/departments/epidemiology-and-public-health-eph/health-systems-research-and-dynamical-modelling.html

**Comment by dhardy** [comment]
Let μ(t) be emergence at time t:

    μ = ρ y / (1 + γ y)

Model adaptation: let y(t) refer to juveniles from the current species, and y̅(t) ["y bar"] refer to juveniles from all competing species. Let us also replace γ with γ̅ ["gamma bar"] since it refers to resources available to all species. We now use the following, where μ, ρ and y are properties of a single species:

    μ_j = ρ_j y_j / (1 + γ̅ y̅)
    γ̅(t) = sum_j γ_j(t - θ_j)
    y̅(t) = sum_j y_j(t - θ_j)

Reversing the new equation for emergence, we obtain γ̅:

    γ̅ = (ρ_j y_j - μ_j) / (y̅ μ_j)

This implies that (ρ y - μ) / μ should be equal for each species. Due especially to how μ is estimated in the model, this is extremely unlikely. I *propose* therefore to set γ̅ as:

    1 / γ̅ = sum_j μ_j y_j / (ρ_j y_j - μ_j)

(which follows intuition, since emergence is maximised by a large 1/γ).

**Comment by dhardy** [comment]
Commit 84ecb75 fixes a bug in the vector model (see email).

Commits 84ecb75..bae59ac add the theoretical minimum code for larval competition, but to little surprise the initialisation fails:

    Low larval resources: -0.0521934

([from this line](https://github.com/SwissTPH/openmalaria/blob/b6eaedaaa1aebc370eb41aa9c3dfa2fbc330e6ec/model/Transmission/Anopheles/SimpleMPDEmergence.cpp#L277)).

**Comment by dhardy** [comment]
... I suspect the mentioned "bug" caused no real issue, except that changes in 1bb9092 were incompatible with the pre-"fix" code. Reasoning: initialisation was still happening for all species, albeit over more cycles.

**Comment by dhardy** [comment]
After discussion with Tom and Nakul, it appears that this model would be tricky to parameterise in such a way that species coexist, and doing so within OpenMalaria would have limited benefits.

We propose not to do this but will leave the issue open to future comments (@obriet).

**Comment by ThomasASmith** [comment]
If we work further on this, I would suggest it should be as a stand-alone ento model, not as part of OpenMalaria
