### ISSUE TITLE
[bug] [schema-33] [output] Values for measure 3 are greater than those for measures 1 or 6

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#51]
There is a problem with the output for summary measure 3 (the number of patent hosts). 

If you look through an example output file, the value for 3 is greater than 1 (the number of infected hosts) and than 6 (total number of infections). This does not make sense.  If you look at the later time steps, there is no malaria in the population, but we still get somewhat large values for 3.

**Comment by nakul7** [comment]
The number of humans with patent infections is sometimes larger than the number of infected humans because the number of humans was being calculated using a stochastic parameterization of rapid diagnostic tests with specificity less than 1. In some settings (especially around elimination) the number of false positives was greater than the number of infections.
